export { default as StepOne } from './StepOne/StepOne';
export { default as StepTwo } from './StepTwo/StepTwo';
export { default as StepThree } from './StepThree/StepThree';
export { default as StepFour } from './StepFour/StepFour';
export { default as StepFive } from './StepFive/StepFive';
export { default as StepSix } from './StepSix/StepSix';
export { default as StepSeven } from './StepSeven/StepSeven';
export { default as StepEight } from './StepEight/StepEight';
export { default as Menu } from './Menu/Menu';
