export const CARGAR_AREA_IMPACTO = 'CARGAR_AREA_IMPACTO';
export const AGREGAR_AREA_IMPACTO = 'AGREGAR_AREA_IMPACTO';
export const EDITAR_AREA_IMPACTO = 'EDITAR_AREA_IMPACTO';
export const ELIMINAR_AREA_IMPACTO = 'ELIMINAR_AREA_IMPACTO';

export const CARGAR_CRITERIO = 'CARGAR_CRITERIO';
export const AGREGAR_CRITERIO = 'AGREGAR_CRITERIO';
export const EDITAR_CRITERIO = 'EDITAR_CRITERIO';
export const ELIMINAR_CRITERIO = 'ELIMINAR_CRITERIO';

export const CARGAR_ACTIVO = 'CARGAR_ACTIVO';
export const AGREGAR_ACTIVO = 'AGREGAR_ACTIVO';
export const EDITAR_ACTIVO = 'EDITAR_ACTIVO';
export const ELIMINAR_ACTIVO = 'ELIMINAR_ACTIVO';

export const CARGAR_REQUERIMIENTO = 'CARGAR_REQUERIMIENTO';
export const AGREGAR_REQUERIMIENTO = 'AGREGAR_REQUERIMIENTO';
export const EDITAR_REQUERIMIENTO = 'EDITAR_REQUERIMIENTO';
export const ELIMINAR_REQUERIMIENTO = 'ELIMINAR_REQUERIMIENTO';

export const CARGAR_CONTENEDOR = 'CARGAR_CONTENEDOR';
export const AGREGAR_CONTENEDOR = 'AGREGAR_CONTENEDOR';
export const EDITAR_CONTENEDOR = 'EDITAR_CONTENEDOR';
export const ELIMINAR_CONTENEDOR = 'ELIMINAR_CONTENEDOR';

export const CARGAR_AREA_PREOCUPACION = 'CARGAR_AREA_PREOCUPACION';
export const AGREGAR_AREA_PREOCUPACION = 'AGREGAR_AREA_PREOCUPACION';
export const EDITAR_AREA_PREOCUPACION = 'EDITAR_AREA_PREOCUPACION';
export const ELIMINAR_AREA_PREOCUPACION = 'ELIMINAR_AREA_PREOCUPACION';

export const CARGAR_CONSECUENCIA = 'CARGAR_CONSECUENCIA';
export const AGREGAR_CONSECUENCIA = 'AGREGAR_CONSECUENCIA';
export const EDITAR_CONSECUENCIA = 'EDITAR_CONSECUENCIA';
export const ELIMINAR_CONSECUENCIA = 'ELIMINAR_CONSECUENCIA';

export const CARGAR_SEVERIDAD = 'CARGAR_SEVERIDAD';
export const AGREGAR_SEVERIDAD = 'AGREGAR_SEVERIDAD';
export const EDITAR_SEVERIDAD = 'EDITAR_SEVERIDAD';

export const CARGAR_CONTROL = 'CARGAR_CONTROL';
export const AGREGAR_CONTROL = 'AGREGAR_CONTROL';
export const EDITAR_CONTROL = 'EDITAR_CONTROL';
export const ELIMINAR_CONTROL = 'ELIMINAR_CONTROL';

export const CARGAR_CUESTIONARIO = 'CARGAR_CUESTIONARIO';
export const AGREGAR_CUESTIONARIO = 'AGREGAR_CUESTIONARIO';
export const EDITAR_CUESTIONARIO = 'EDITAR_CUESTIONARIO';
